# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tests"
  test-api-client:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: c-hive/gha-yarn-cache@v1
    - name: install modules
      run: yarn
      working-directory: ./sources/api-client
    - uses: mattallty/jest-github-action@v1
      with:
        test-command: "yarn test"
        coverage-comment: false
        working-directory: ./sources/api-client

  lint-api-client:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: c-hive/gha-yarn-cache@v1
    - name: install modules
      run: yarn
      working-directory: ./sources/api-client
    - name: run tests
      run: npx eslint .
      working-directory: ./sources/api-client
    - name: generate report
      run: npx eslint --output-file eslint_report.json --format json .
      working-directory: ./sources/api-client
      continue-on-error: true
    - name: Annotate Code Linting Results
      uses: ataylorme/eslint-annotate-action@1.2.0
      with:
        report-json: "eslint_report.json"
    - name: Upload ESLint report
      uses: actions/upload-artifact@v2
      with:
        name: eslint_report.json
        path: eslint_report.json