module.exports = {
	MIN_ID: 1, //a@b.c
	MIN_STRING: 1,
	MAX_STRING: 45,
	MAX_STRING_LONG: 255,
	MIN_EMAIL: 5, //a@b.c
	MAX_EMAIL: 255,
	MIN_TEXT: 1,
	MAX_TEXT: 65535,
	COLOR_SIZE: 7,
	COLOR_PATTERN: /^#[0-9A-Fa-f]+$/,
	MIN_PASSWORD: 1,
	MAX_PASSWORD: 50,
};
